version: '3.8'
name: web-proxy
services:
  php:
    build:
      target: php_dev
    container_name: ${COMPOSE_PROJECT_NAME}-php-dev
    image: max-antipin/${COMPOSE_PROJECT_NAME}-php-dev
    restart: unless-stopped
    volumes:
      - .:/var/www/html/
  webserver:
    configs:
      - source: nginx_conf
        target: /etc/nginx/templates/default.conf.template
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-dev
    environment:
      - SERVER_NAME=dolly-proxy.local
      - DOLLY_SERVER_NAME=dolly-sites.local
    image: nginx:${NGINX_VERSION:-1.24}-alpine
    ports:
      - target: 80
        published: ${SERVER_PORT:-80}
        protocol: tcp
    restart: unless-stopped
configs:
  nginx_conf:
    file: ./.docker/nginx/default.conf.template
