version: '3.8'
name: 'web-proxy'
services:
  php:
#    configs:
 #     - source: phpunit
  #      target: /usr/src/app/phpunit.xml
   #   - source: xdebug
    #    target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    container_name: ${COMPOSE_PROJECT_NAME}-php-app
    image: localhost:5000/max-antipin/web-proxy-php-app
    restart: always
  webserver:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      - SERVER_NAME=dolly-proxy.local
      - DOLLY_SERVER_NAME=dolly-sites.local
#    env_file:
#      - ./.env.app
    image: localhost:5000/max-antipin/web-proxy-nginx
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
#    read_only: true
    restart: always
#    volumes:
#      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
#      - ./docker/nginx/x-catch-all.conf:/etc/nginx/conf.d/x-catch-all.conf:ro
#      - ./docker/nginx/x-catch-all.conf:/etc/nginx/x-catch-all.conf:ro
#      - ./docker/nginx-dev/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./public/:/var/www/html/public/:ro
#      - ./public-dolly/:/var/www/html/public-dolly/:ro
#      - ./http_404.html:/usr/share/nginx/html/http_404.html:ro
#      - nginx-cache:/var/cache/nginx/
#      - nginx-pid:/var/run/
#      - nginx-log:/var/log/nginx/
#      - SCRIPT_DIR=/my/sub-folder/
#      - DOLLY_DIR=/dolly-sites/v2/
#volumes:
#  nginx-cache:
#  nginx-pid:
#  nginx-log:
#configs:
 # phpunit:
  #  file: ./phpunit.xml
  #xdebug:
   # file: ./xdebug.ini
