version: '3.8'
name: web-proxy-dev
services:
  php:
    build:
      target: php_dev
#    configs:
#      - source: dolly_conf
#        target: /var/www/html/conf.php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    image: max-antipin/${COMPOSE_PROJECT_NAME}-php
    restart: unless-stopped
    volumes:
      - ../:/var/www/html/
  webserver:
    configs:
      - source: nginx_conf
        target: /etc/nginx/templates/default.conf.template
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    env_file: ${SERVER_ENV_FILE:-./.env.app.dist}
    image: nginx:1.24-alpine
    ports:
      - target: 80
        published: ${SERVER_PORT:-80}
        protocol: tcp
    restart: unless-stopped
configs:
  nginx_conf:
    file: ./nginx/default.conf.template
