version: '3.8'
name: web-proxy
services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php-app-${APP_TAG:-test}
    image: localhost:5000/max-antipin/web-proxy-php-app:${APP_TAG:-test}
    restart: unless-stopped
  webserver:
    configs:
      - source: nginx_conf
        target: /etc/nginx/templates/default.conf.template
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      - SERVER_NAME=dolly-proxy.local
      - DOLLY_SERVER_NAME=dolly-sites.local
    image: nginx:${NGINX_VERSION:-1.24}-alpine
    ports:
      - target: 80
        published: ${SERVER_PORT:-80}
        protocol: tcp
    read_only: true
    restart: unless-stopped
    volumes:
      - nginx-cache:/var/cache/nginx/
      - nginx-conf:/etc/nginx/conf.d/
      - nginx-pid:/var/run/
      - nginx-log:/var/log/nginx/
configs:
  nginx_conf:
    file: ./nginx/default.conf.template
volumes:
  nginx-cache:
  nginx-conf:
  nginx-pid:
  nginx-log:
